# https://home.miot-spec.com/spec/dmaker.fan.1c

external_components:
  source: github://andrei-marinache/esphome-miot@main

esphome:
  name: standing-fan
  friendly_name: Smart Standing Fan 2 Lite
  comment: Xiaomi Mi Smart Standing Fan 2 Lite (dmaker.fan.1c)
  project:
    name: "andrei-marinache.esphome-miot"
    version: "dmaker.fan.p18"

esp8266:
  board: esp_wroom_02

logger:
  level: DEBUG
  # Important: Disable UART1 logging to avoid hardware errors on main UART0
  baud_rate: 0

api:
  encryption:
    key: !secret api_encryption_key
  reboot_timeout: 0s
  services:
    - service: mcu_command
      variables:
        command: string
      then:
        - lambda: 'id(miot_main).queue_command(command);'

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    password: !secret wifi_ap_password

captive_portal:

uart:
  tx_pin: GPIO15
  rx_pin: GPIO13
  baud_rate: 115200

miot:
  id: miot_main

fan:
  - platform: "miot"
    name: "Fan"
    state:
      miot_siid: 2
      miot_piid: 1
    speed:
      miot_siid: 2
      miot_piid: 2
      min_value: 1
      max_value: 3
    oscillating:
      miot_siid: 2
      miot_piid: 3
switch:
  - platform: "miot"
    miot_siid: 2
    miot_piid: 12
    name: "Indicator Lights"
    icon: "mdi:lightbulb"
    entity_category: config
  - platform: "miot"
    miot_siid: 2
    miot_piid: 11
    name: "Notification Sounds"
    icon: "mdi:volume-high"
    entity_category: config
  - platform: "miot"
    miot_siid: 3
    miot_piid: 1
    name: "Child Lock"
    icon: "mdi:lock"
    entity_category: config

select:
  - platform: "miot"
    id: "mode"
    miot_siid: 2
    miot_piid: 7
    name: "Mode"
    icon: "mdi:leaf"
    options:
      0: "Direct Breeze"
      1: "Sleep Mode"

number:
  - platform: "miot"
    miot_siid: 2
    miot_piid: 10
    name: "Off Delay"
    icon: "mdi:clock-outline"
    unit_of_measurement: "min"
    device_class: duration
    min_value: 0
    max_value: 480
    step: 1

button:
  - platform: "miot"
    miot_siid: 2
    miot_aiid: 1
    name: "Toggle Power"
    icon: "mdi:power-cycle"
